# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c373128cf5020329485341c4c2951d99e1f66493b5e0c8f3e64200aad23c5051bad8524619367fe161180f9d770a31254043d7238fc2d7c8aa3b7d997f012a

test:
  secret_key_base: 076412ee49b89147fbd54d744580387b4fbb29a77d9f5226f1d27196c5a2532f1b3293ee16f8b74c453ba0dc5b7cd72d4d2acd5397b68d743c53f841e0c2cd85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
